[package]
edition = "2021"
name = "gcs-upload"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-cloud-auth = "0.8.1"
google-cloud-storage = "0.8.1"
tokio = {version = "1.25.0", features = ["rt-multi-thread"]}
